openapi: 3.0.3
info:
  title: UserEvent Reader API
  version: 1.0.0

paths:
  /events:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserEvent'
          description: "OK"
components:
  schemas:
    UserEvent:
      type: object
      properties:
        eventType:
          type: string
        eventTime:
          type: string
          format: date-time